(function(){
var root=document.getElementById('lynx-livechat');if(!root)return;
var panel=root.querySelector('.lc-panel'),start=root.querySelector('.lc-start'),room=root.querySelector('.lc-room'),messages=root.querySelector('.lc-messages'),typingIndicator=root.querySelector('.lc-typing'),textInput=root.querySelector('.lc-text'),error=root.querySelector('.lc-error'),invite=root.querySelector('.lc-invitation'),launch=root.querySelector('.lc-launch'),begin=root.querySelector('.lc-begin'),token=localStorage.getItem('lynx_livechat_token')||'',visitorKey=localStorage.getItem('lynx_livechat_visitor')||'',activeInvitation=0,last=0,timer,typingTimer=0,lastTypingPing=0,messagesLoaded=false,audioContext;
if(!/^[a-f0-9]{64}$/.test(visitorKey)){var bytes=new Uint8Array(32);crypto.getRandomValues(bytes);visitorKey=Array.prototype.map.call(bytes,function(x){return x.toString(16).padStart(2,'0')}).join('');localStorage.setItem('lynx_livechat_visitor',visitorKey)}
function notify(open){if(window.parent!==window)window.parent.postMessage({type:'lynx-livechat:size',open:open},'*')}
function api(data){return fetch(root.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(function(r){return r.json().then(function(j){if(!r.ok)throw new Error(j.error||'Chat request failed.');return j})})}
function unlockAudio(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume()}catch(e){}}
function sound(){try{unlockAudio();var oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=660;gain.gain.setValueAtTime(.1,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.2);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.2)}catch(e){}}
function showInvitation(item){if(token||!item||activeInvitation===item.id)return;activeInvitation=item.id;invite.querySelector('.lc-invite-operator').textContent=item.operator_name||'Support';invite.querySelector('.lc-invite-message').textContent=item.message;invite.hidden=false;launch.hidden=true;notify(true)}
function hideInvitation(){activeInvitation=0;invite.hidden=true;if(panel.hidden)launch.hidden=false;notify(!panel.hidden)}
function presence(){var params=new URLSearchParams(location.search);api({action:'presence',visitor_key:visitorKey,page_url:params.get('page')||location.href,referrer:params.get('referrer')||document.referrer}).then(function(r){if(r.invitation)showInvitation(r.invitation);else if(activeInvitation)hideInvitation()}).catch(function(){})}
function respond(response){if(!activeInvitation)return;var id=activeInvitation,button=invite.querySelector('.lc-invite-accept');button.disabled=true;api({action:'invitation_response',visitor_key:visitorKey,invitation_id:id,response:response}).then(function(r){hideInvitation();if(response==='accept'){token=r.token;localStorage.setItem('lynx_livechat_token',token);messages.innerHTML='';last=0;add(r.messages||[]);panel.hidden=false;launch.hidden=true;enter()}}).catch(function(e){hideInvitation();showError(e)}).then(function(){button.disabled=false})}
function showError(e){error.textContent=e.message||e}
function add(items){items.forEach(function(m){var d=document.createElement('div'),meta=document.createElement('div'),body=document.createElement('div'),time=new Date(+m.created_at*1000);d.className='lc-message '+m.sender;meta.className='lc-message-meta';meta.textContent=m.sender_name+' · '+time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});body.className='lc-message-body';body.textContent=m.body;d.appendChild(meta);d.appendChild(body);messages.appendChild(d);last=Math.max(last,+m.id)});if(items.length)messages.scrollTop=messages.scrollHeight}
function poll(){if(!token)return;api({action:'poll',token:token,after:last}).then(function(r){if(messagesLoaded&&r.messages.some(function(m){return m.sender==='operator'}))sound();add(r.messages);messagesLoaded=true;typingIndicator.hidden=!r.operator_typing;if(r.status==='closed')showError('This chat has been closed.')}).catch(function(e){if(e.message==='Chat session not found.'){token='';localStorage.removeItem('lynx_livechat_token');start.hidden=false;room.hidden=true}})}
function enter(){start.hidden=true;room.hidden=false;poll();clearInterval(timer);timer=setInterval(poll,3000)}
launch.onclick=function(){unlockAudio();notify(true);panel.hidden=false;this.hidden=true;this.setAttribute('aria-expanded','true');if(token)enter()};
root.querySelector('.lc-close').onclick=function(){var closingToken=token;function reset(){clearInterval(timer);token='';last=0;messagesLoaded=false;localStorage.removeItem('lynx_livechat_token');messages.innerHTML='';typingIndicator.hidden=true;error.textContent='';room.hidden=true;start.hidden=false;panel.hidden=true;launch.hidden=false;launch.setAttribute('aria-expanded','false');notify(false)}if(closingToken)api({action:'close',token:closingToken}).then(reset).catch(showError);else reset()};
invite.querySelector('.lc-invite-accept').onclick=function(){unlockAudio();respond('accept')};invite.querySelector('.lc-invite-decline').onclick=invite.querySelector('.lc-invite-close').onclick=function(){respond('decline')};
start.onsubmit=function(e){e.preventDefault();showError('');begin.disabled=true;begin.querySelector('span').textContent='Connecting…';api({action:'start',visitor_key:visitorKey,name:root.querySelector('.lc-name').value,email:root.querySelector('.lc-email').value,department_id:root.querySelector('.lc-department').value}).then(function(r){token=r.token;localStorage.setItem('lynx_livechat_token',token);add(r.messages||[]);enter()}).catch(showError).then(function(){begin.disabled=false;begin.querySelector('span').textContent='Start conversation'})};
textInput.addEventListener('input',function(){if(!token)return;var now=Date.now();if(now-lastTypingPing>2000){lastTypingPing=now;api({action:'typing',token:token,typing:true}).catch(function(){})}clearTimeout(typingTimer);typingTimer=setTimeout(function(){api({action:'typing',token:token,typing:false}).catch(function(){})},3000)});
room.querySelector('form').onsubmit=function(e){e.preventDefault();var body=textInput.value.trim();if(!body)return;api({action:'typing',token:token,typing:false});api({action:'send',token:token,body:body}).then(function(){textInput.value='';poll()}).catch(showError)};
presence();setInterval(presence,5000);notify(false)
})();
