<?php
function hd_module_escape($value){$db=$GLOBALS['_lynxhd_mysql_connection']??null;return $db?mysqli_real_escape_string($db,(string)$value):addslashes((string)$value);}
function hd_modules_registry_ready(){global $pre;return mysql_query("CREATE TABLE IF NOT EXISTS {$pre}module (id INT UNSIGNED NOT NULL AUTO_INCREMENT,module_dir VARCHAR(80) NOT NULL,module_name VARCHAR(150) NOT NULL,version VARCHAR(30) NOT NULL DEFAULT '',author VARCHAR(150) NOT NULL DEFAULT '',description TEXT,installed TINYINT(1) NOT NULL DEFAULT 0,enabled TINYINT(1) NOT NULL DEFAULT 0,updated_at INT UNSIGNED NOT NULL,PRIMARY KEY(id),UNIQUE KEY module_dir(module_dir)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");}
function hd_module_manifest($dir){if(!preg_match('/^[a-z0-9_-]+$/',$dir))return false;$file=__DIR__."/$dir/module.json";if(!is_file($file))return false;$data=json_decode(file_get_contents($file),true);if(!is_array($data))return false;$data['dir']=$dir;return $data;}
function hd_modules_available(){ $items=array();foreach(scandir(__DIR__) as $dir){$manifest=hd_module_manifest($dir);if($manifest)$items[$dir]=$manifest;}ksort($items);return $items; }
function hd_module_load($dir){$manifest=hd_module_manifest($dir);if(!$manifest)return false;$file=__DIR__."/$dir/bootstrap.php";if(!is_file($file))return false;require_once $file;return $manifest;}
function hd_module_sync($dir,$installed,$enabled){global $pre;$m=hd_module_manifest($dir);if(!$m||!hd_modules_registry_ready())return false;$d=hd_module_escape($dir);$name=hd_module_escape($m['name']??$dir);$version=hd_module_escape($m['version']??'');$author=hd_module_escape($m['author']??'');$description=hd_module_escape($m['description']??'');$now=time();if(get_row_count("SELECT COUNT(*) FROM {$pre}module WHERE module_dir='$d'"))return mysql_query("UPDATE {$pre}module SET module_name='$name',version='$version',author='$author',description='$description',installed=".(int)$installed.",enabled=".(int)$enabled.",updated_at=$now WHERE module_dir='$d'");return mysql_query("INSERT INTO {$pre}module(module_dir,module_name,version,author,description,installed,enabled,updated_at) VALUES('$d','$name','$version','$author','$description',".(int)$installed.",".(int)$enabled.",$now)");}
function hd_module_state($dir){global $pre;if(!hd_modules_registry_ready())return array('installed'=>false,'enabled'=>false);$d=hd_module_escape($dir);$r=mysql_query("SELECT installed,enabled FROM {$pre}module WHERE module_dir='$d' LIMIT 1");$row=$r?mysql_fetch_array($r,MYSQLI_ASSOC):false;return array('installed'=>$row&&(bool)$row['installed'],'enabled'=>$row&&(bool)$row['enabled']);}
function hd_module_action($dir,$action){$m=hd_module_load($dir);if(!$m)return false;$prefix=str_replace('-','_',$dir);$fn=$prefix.'_'.$action;if(!function_exists($fn))return false;$ok=(bool)$fn();if(!$ok)return false;if($action==='install'){ $enable=$prefix.'_enable';if(function_exists($enable)&&!$enable())return false;return hd_module_sync($dir,true,true);}if($action==='uninstall')return hd_module_sync($dir,false,false);if($action==='enable')return hd_module_sync($dir,true,true);if($action==='disable')return hd_module_sync($dir,true,false);return true;}
function hd_module_enabled($dir){$state=hd_module_state($dir);return $state['installed']&&$state['enabled'];}
