<?php
////////////////////////////////////////////////////////////////////
// LynxHD Formely ColdBrew Help Desk
// License info can be found in license.txt. You must leave this notice as is.
////////////////////////////////////////////////////////////////////
include "../include/settings.php";
include "../include/include.php";
$HD_CURPAGE = $HD_URL_DEPARTMENT;
if (($_SESSION['login_type'] ?? $LOGIN_INVALID) == $LOGIN_INVALID) { Header("Location: {$HD_URL_LOGIN}?redirect=" . urlencode($HD_CURPAGE)); exit; }

function dept_escape($value) { $db=$GLOBALS['_lynxhd_mysql_connection']??null; return $db?mysqli_real_escape_string($db,(string)$value):addslashes((string)$value); }
function dept_admin($id) { global $pre; $uid=(int)$_SESSION['user']['id']; $id=(int)$id; return get_row_count("SELECT COUNT(*) FROM {$pre}privilege WHERE user_id=$uid AND dept_id=$id AND admin=1")>0; }
$uid=(int)$_SESSION['user']['id'];
$global_priv=get_row_count("SELECT COUNT(*) FROM {$pre}privilege WHERE user_id=$uid AND dept_id=0 AND admin=1")>0;
$csrf=$_SESSION['department_csrf']??''; if($csrf===''){ $csrf=bin2hex(random_bytes(32)); $_SESSION['department_csrf']=$csrf; }
$cmd=(string)($_POST['cmd']??''); $msg='';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && (!isset($_POST['csrf_token']) || !hash_equals($csrf, (string)$_POST['csrf_token']))) { $msg='<div class="alert alert-danger">The request could not be verified. Please try again.</div>'; $cmd=''; }

if($cmd==='add'&&$global_priv){
  $name=trim((string)($_POST['name']??'')); $safe=dept_escape($name);
  if($name==='') $msg='<div class="alert alert-danger">Enter a department name.</div>';
  elseif(get_row_count("SELECT COUNT(*) FROM {$pre}dept WHERE name='$safe'")) $msg='<div class="alert alert-danger">A department with that name already exists.</div>';
  else { $r=mysql_fetch_array(mysql_query("SELECT COALESCE(MAX(sortnum),0) FROM {$pre}dept"))?:array(0); mysql_query("INSERT INTO {$pre}dept(name,sortnum) VALUES('$safe',".((int)$r[0]+1).")"); $msg='<div class="alert alert-success">Department created.</div>'; }
} elseif($cmd==='options'&&$global_priv){
  $id=(int)($_POST['dept_id']??0); $name=trim((string)($_POST['name']??'')); $safe=dept_escape($name); $desc=dept_escape(trim((string)($_POST['description']??'')));
  if($name==='') $msg='<div class="alert alert-danger">Enter a department name.</div>';
  elseif(get_row_count("SELECT COUNT(*) FROM {$pre}dept WHERE name='$safe' AND id!=$id")) $msg='<div class="alert alert-danger">A department with that name already exists.</div>';
  else { $options=isset($_POST['invisible'])?(int)$HD_DEPARTMENT_INVISIBLE:0; mysql_query("UPDATE {$pre}dept SET name='$safe',description='$desc',options=$options WHERE id=$id"); $msg='<div class="alert alert-success">Department updated.</div>'; }
} elseif(($cmd==='moveup'||$cmd==='movedown')&&$global_priv){
  $id=(int)($_POST['dept_id']??0); $cur=mysql_fetch_array(mysql_query("SELECT sortnum FROM {$pre}dept WHERE id=$id"));
  if($cur){$op=$cmd==='moveup'?'<':'>'; $order=$cmd==='moveup'?'DESC':'ASC'; $other=mysql_fetch_array(mysql_query("SELECT id,sortnum FROM {$pre}dept WHERE sortnum $op ".(int)$cur['sortnum']." ORDER BY sortnum $order LIMIT 1")); if($other){mysql_query("UPDATE {$pre}dept SET sortnum=".(int)$other['sortnum']." WHERE id=$id");mysql_query("UPDATE {$pre}dept SET sortnum=".(int)$cur['sortnum']." WHERE id=".(int)$other['id']);}}
} elseif($cmd==='delete'&&$global_priv){
  $id=(int)($_POST['dept_id']??0); if($id){$tickets=mysql_query("SELECT id FROM {$pre}ticket WHERE dept_id=$id");while($tickets&&($t=mysql_fetch_array($tickets))){$tid=(int)$t['id'];if(is_dir("$HD_TICKET_FILES/$tid"))system("rm -rf ".escapeshellarg("$HD_TICKET_FILES/$tid"));mysql_query("DELETE FROM {$pre}post WHERE ticket_id=$tid");mysql_query("DELETE FROM {$pre}message WHERE ticket_id=$tid");}foreach(array('ticket','field','privilege','reply','pop') as $table)mysql_query("DELETE FROM {$pre}$table WHERE dept_id=$id");mysql_query("DELETE FROM {$pre}dept WHERE id=$id");$msg='<div class="alert alert-success">Department deleted.</div>';}
} elseif($cmd==='adduser'){
  $id=(int)($_POST['dept_id']??0);$user=(int)($_POST['user']??0);if(($global_priv||dept_admin($id))&&$user&&get_row_count("SELECT COUNT(*) FROM {$pre}user WHERE id=$user")){mysql_query("DELETE FROM {$pre}privilege WHERE user_id=$user AND dept_id=$id");mysql_query("INSERT INTO {$pre}privilege(dept_id,user_id,admin) VALUES($id,$user,".(isset($_POST['admin'])?1:0).")");$msg='<div class="alert alert-success">User assignment saved.</div>';}
} elseif($cmd==='unassign'){
  $id=(int)($_POST['dept_id']??0);$user=(int)($_POST['user_id']??0);if(($global_priv||dept_admin($id))&&!get_row_count("SELECT COUNT(*) FROM {$pre}user WHERE id=$user AND admin=1")){mysql_query("DELETE FROM {$pre}privilege WHERE user_id=$user AND dept_id=$id");$msg='<div class="alert alert-success">User unassigned.</div>';}
} elseif($cmd==='fields'&&$global_priv){
  $id=(int)($_POST['dept_id']??0);$res=mysql_query("SELECT id FROM {$pre}field WHERE dept_id=$id");while($res&&($f=mysql_fetch_array($res))){$fid=(int)$f['id'];$name=trim((string)($_POST['field'][$fid]??''));if($name!=='')mysql_query("UPDATE {$pre}field SET name='".dept_escape($name)."',required=".(isset($_POST['required'][$fid])?1:0)." WHERE id=$fid AND dept_id=$id");}$new=trim((string)($_POST['newfield']??''));if($new!==''){ $safe=dept_escape($new);if(!get_row_count("SELECT COUNT(*) FROM {$pre}field WHERE name='$safe' AND (dept_id=$id OR dept_id=0)"))mysql_query("INSERT INTO {$pre}field(name,required,dept_id) VALUES('$safe',".(isset($_POST['newrequired'])?1:0).",$id)");}$msg='<div class="alert alert-success">Custom fields updated.</div>';
} elseif($cmd==='fielddel'&&$global_priv){$id=(int)($_POST['dept_id']??0);$fid=(int)($_POST['field_id']??0);mysql_query("DELETE FROM {$pre}field WHERE id=$fid AND dept_id=$id");$msg='<div class="alert alert-success">Custom field removed.</div>';}

$departments=mysql_query("SELECT d.*,(SELECT COUNT(*) FROM {$pre}ticket t WHERE t.dept_id=d.id) tickets,(SELECT COUNT(*) FROM {$pre}field f WHERE f.dept_id=d.id) fields,(SELECT COUNT(*) FROM {$pre}privilege p WHERE p.dept_id=d.id) users FROM {$pre}dept d ORDER BY d.sortnum,d.name");
$all_users=array();$ur=mysql_query("SELECT id,name,admin FROM {$pre}user ORDER BY name");while($ur&&($u=mysql_fetch_array($ur,MYSQLI_ASSOC)))$all_users[]=$u;
$script_name='Departments'; include "./include/header.php";
?>
<div class="d-sm-flex align-items-center justify-content-between mb-4"><div><h1 class="h3 mb-1 text-gray-800">Departments</h1><p class="mb-0 text-muted">Organize support queues, staff access, and ticket fields.</p></div><?php if($global_priv):?><button class="btn btn-primary btn-sm mt-3 mt-sm-0" data-toggle="collapse" data-target="#new-department"><i class="fas fa-plus mr-1"></i>New department</button><?php endif;?></div>
<?php echo $msg ?>
<?php if($global_priv):?><div class="collapse <?php echo $cmd==='add'&&$msg?'show':''?>" id="new-department"><div class="card shadow-sm mb-4 border-left-primary"><div class="card-body"><form method="post" class="form-row align-items-end"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="cmd" value="add"><div class="form-group col-md-9 mb-md-0"><label for="new-dept-name">Department name</label><input class="form-control" id="new-dept-name" name="name" maxlength="255" required placeholder="For example, Billing or Technical Support"></div><div class="col-md-3"><button class="btn btn-primary btn-block">Create department</button></div></form></div></div></div><?php endif;?>
<?php $count=0;while($departments&&($d=mysql_fetch_array($departments,MYSQLI_ASSOC))):$count++;$id=(int)$d['id'];$member_admin=$global_priv||dept_admin($id);?>
<section class="card shadow-sm mb-4 department-card"><div class="card-header bg-white py-3 d-flex flex-wrap align-items-center justify-content-between"><div class="d-flex align-items-center"><span class="department-icon mr-3"><i class="fas fa-building"></i></span><div><h2 class="h5 mb-1 text-gray-900"><?php echo field($d['name'])?><?php if($d['options']&$HD_DEPARTMENT_INVISIBLE):?><span class="badge badge-secondary ml-1">Staff only</span><?php endif;?></h2><div class="small text-muted"><span class="mr-3"><i class="fas fa-ticket-alt mr-1"></i><?php echo (int)$d['tickets']?> tickets</span><span class="mr-3"><i class="fas fa-users mr-1"></i><?php echo (int)$d['users']?> users</span><span><i class="fas fa-list-alt mr-1"></i><?php echo (int)$d['fields']?> fields</span></div></div></div><button class="btn btn-sm btn-outline-primary mt-2 mt-sm-0" data-toggle="collapse" data-target="#dept-<?php echo $id?>"><i class="fas fa-cog mr-1"></i>Manage</button></div>
<div class="collapse" id="dept-<?php echo $id?>"><div class="card-body">
<?php if($global_priv):?><div class="text-right mb-3"><form method="post" class="d-inline"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="dept_id" value="<?php echo $id?>"><button class="btn btn-sm btn-light" name="cmd" value="moveup" title="Move up"><i class="fas fa-arrow-up"></i></button><button class="btn btn-sm btn-light" name="cmd" value="movedown" title="Move down"><i class="fas fa-arrow-down"></i></button></form><?php if($id):?><form method="post" class="d-inline ml-2" onsubmit="return confirm('Delete this department and all of its tickets? This cannot be undone.')"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="dept_id" value="<?php echo $id?>"><button class="btn btn-sm btn-outline-danger" name="cmd" value="delete"><i class="fas fa-trash mr-1"></i>Delete</button></form><?php endif;?></div>
<form method="post" class="mb-4"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="cmd" value="options"><input type="hidden" name="dept_id" value="<?php echo $id?>"><h3 class="h6 font-weight-bold text-primary">Settings</h3><div class="form-row"><div class="form-group col-md-5"><label>Name</label><input class="form-control" name="name" maxlength="255" required value="<?php echo field($d['name'])?>"></div><div class="form-group col-md-7"><label>Description</label><input class="form-control" name="description" maxlength="255" value="<?php echo field($d['description'])?>" placeholder="What does this department handle?"></div></div><div class="d-flex justify-content-between"><div class="custom-control custom-switch"><input class="custom-control-input" id="hidden-<?php echo $id?>" type="checkbox" name="invisible" <?php echo ($d['options']&$HD_DEPARTMENT_INVISIBLE)?'checked':''?>><label class="custom-control-label" for="hidden-<?php echo $id?>">Hide from customers</label></div><button class="btn btn-sm btn-primary">Save settings</button></div></form>
<hr><form method="post" class="my-4"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="cmd" value="fields"><input type="hidden" name="dept_id" value="<?php echo $id?>"><h3 class="h6 font-weight-bold text-primary">Ticket custom fields</h3><?php $fr=mysql_query("SELECT * FROM {$pre}field WHERE dept_id=$id ORDER BY id");while($fr&&($f=mysql_fetch_array($fr,MYSQLI_ASSOC))):$fid=(int)$f['id'];?><div class="form-row align-items-center mb-2"><div class="col-md-7"><input class="form-control form-control-sm" name="field[<?php echo $fid?>]" value="<?php echo field($f['name'])?>"></div><div class="col-md-3"><div class="custom-control custom-checkbox"><input class="custom-control-input" id="req-<?php echo $fid?>" type="checkbox" name="required[<?php echo $fid?>]" <?php echo $f['required']?'checked':''?>><label class="custom-control-label" for="req-<?php echo $fid?>">Required</label></div></div><div class="col-md-2 text-right"><button class="btn btn-sm btn-link text-danger" form="delete-field-<?php echo $fid?>">Remove</button></div></div><?php endwhile;?><div class="form-row align-items-center mt-3"><div class="col-md-7"><input class="form-control form-control-sm" name="newfield" maxlength="255" placeholder="Add a new field"></div><div class="col-md-3"><div class="custom-control custom-checkbox"><input class="custom-control-input" id="newreq-<?php echo $id?>" type="checkbox" name="newrequired"><label class="custom-control-label" for="newreq-<?php echo $id?>">Required</label></div></div><div class="col-md-2 text-right"><button class="btn btn-sm btn-primary">Update fields</button></div></div></form><?php $fr=mysql_query("SELECT id FROM {$pre}field WHERE dept_id=$id");while($fr&&($f=mysql_fetch_array($fr))):?><form id="delete-field-<?php echo (int)$f['id']?>" method="post" onsubmit="return confirm('Remove this custom field?')"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="cmd" value="fielddel"><input type="hidden" name="dept_id" value="<?php echo $id?>"><input type="hidden" name="field_id" value="<?php echo (int)$f['id']?>"></form><?php endwhile;?><?php endif;?>
<hr><div class="mt-4"><h3 class="h6 font-weight-bold text-primary">Assigned users</h3><div class="list-group mb-3"><?php $ar=mysql_query("SELECT u.id,u.name,u.admin master,p.admin deptadmin FROM {$pre}user u JOIN {$pre}privilege p ON p.user_id=u.id WHERE p.dept_id=$id ORDER BY u.name");$ac=0;while($ar&&($a=mysql_fetch_array($ar,MYSQLI_ASSOC))):$ac++;?><div class="list-group-item d-flex justify-content-between align-items-center"><div><a class="font-weight-bold" href="<?php echo $HD_URL_USER?>?cmd=view&amp;id=<?php echo (int)$a['id']?>"><?php echo field($a['name'])?></a><?php if($a['master']):?><span class="badge badge-dark ml-2">Master admin</span><?php elseif($a['deptadmin']):?><span class="badge badge-info ml-2">Department admin</span><?php endif;?></div><?php if($member_admin&&!$a['master']):?><form method="post" onsubmit="return confirm('Unassign this user?')"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="cmd" value="unassign"><input type="hidden" name="dept_id" value="<?php echo $id?>"><input type="hidden" name="user_id" value="<?php echo (int)$a['id']?>"><button class="btn btn-sm btn-link text-danger">Unassign</button></form><?php endif;?></div><?php endwhile;if(!$ac):?><div class="list-group-item text-muted">No users assigned.</div><?php endif;?></div>
<?php if($member_admin):?><form method="post" class="form-row align-items-end"><input type="hidden" name="csrf_token" value="<?php echo field($csrf)?>"><input type="hidden" name="cmd" value="adduser"><input type="hidden" name="dept_id" value="<?php echo $id?>"><div class="form-group col-md-6 mb-md-0"><label>Add user</label><select class="form-control form-control-sm" name="user" required><option value="">Choose a user</option><?php foreach($all_users as $u):if($u['admin'])continue;?><option value="<?php echo (int)$u['id']?>"><?php echo field($u['name'])?></option><?php endforeach;?></select></div><div class="form-group col-md-3 mb-md-0"><div class="custom-control custom-checkbox"><input class="custom-control-input" id="admin-<?php echo $id?>" type="checkbox" name="admin"><label class="custom-control-label" for="admin-<?php echo $id?>">Department admin</label></div></div><div class="col-md-3"><button class="btn btn-sm btn-outline-primary btn-block">Assign user</button></div></form><?php endif;?></div></div></div></section>
<?php endwhile;if(!$count):?><div class="card shadow-sm"><div class="card-body text-center py-5 text-muted"><i class="fas fa-building fa-3x mb-3 text-gray-300"></i><h2 class="h5">No departments yet</h2><p class="mb-0">Create one to organize incoming support requests.</p></div></div><?php endif;?>
<style>.department-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:10px;background:#eef2ff;color:#4e73df}.department-card .card-header{border-bottom:0}.department-card .collapse.show{border-top:1px solid #e3e6f0}</style>
<?php include "./include/footer.php"; ?>
