<?php
include '../include/settings.php';
include '../include/include.php';
include '../modules/livechat/bootstrap.php';
include '../modules/system.php';
$HD_CURPAGE = 'livechat.php';
if (($_SESSION['login_type'] ?? $LOGIN_INVALID) == $LOGIN_INVALID) { header('Location: index.php?redirect=livechat.php'); exit; }
$global_priv = get_row_count("SELECT COUNT(*) FROM {$pre}privilege WHERE user_id='" . (int)$_SESSION['user']['id'] . "' AND dept_id='0'");
if (!$global_priv) { header("Location: $HD_URL_BROWSE"); exit; }
$installed = livechat_installed();
$enabled = $installed && livechat_enabled();
$canned_ready = $installed && livechat_ensure_canned_messages();
$script_name = 'Live Chat';
include './include/header.php';
?>
<div class="d-sm-flex align-items-center justify-content-between mb-4"><div><h1 class="h3 mb-1 text-gray-800">Live chat</h1><p class="mb-0 text-muted">Talk to visitors from the support site in real time.</p></div><a class="btn btn-outline-primary mt-3 mt-sm-0" href="livechatsettings.php"><i class="fas fa-cog mr-1"></i>Chat settings</a></div>
<?php if (!$installed): ?>
<div class="alert alert-info shadow-sm">Live Chat is not installed. <a class="alert-link" href="modules.php">Install it from Modules</a>.</div>
<?php elseif (!$enabled): ?>
<div class="alert alert-warning shadow-sm">Live Chat is disabled. <a class="alert-link" href="livechatsettings.php">Enable it in Chat settings</a>.</div>
<?php else: ?>
<div id="live-visitor-monitor" data-api="../modules/livechat/api.php" class="mb-4">
  <div class="card shadow-sm mb-4 border-0">
    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center"><div><h2 class="h5 mb-1 text-gray-900"><i class="fas fa-hourglass-half text-warning mr-2"></i>Visitors waiting <span class="badge badge-warning ml-1" id="waiting-count">0</span></h2><small class="text-muted">Visitors who started a conversation and are waiting for an operator.</small></div><span class="small text-muted visitor-monitor-state">Updating…</span></div>
    <div class="table-responsive"><table class="table table-hover mb-0 visitor-table"><thead><tr><th>Name</th><th>Actions</th><th>Visitor's address</th><th>State</th><th>Department</th><th>Total time</th><th>Waiting time</th><th>Misc</th></tr></thead><tbody id="waiting-visitors"><tr><td colspan="8" class="text-center text-muted py-3">Loading…</td></tr></tbody></table></div>
  </div>
  <div class="card shadow-sm border-0">
    <div class="card-header bg-white py-3"><h2 class="h5 mb-1 text-gray-900"><i class="fas fa-users text-primary mr-2"></i>Visitors on site <span class="badge badge-primary ml-1" id="onsite-count">0</span></h2><small class="text-muted">Visitors currently viewing a page where the live-chat widget is loaded.</small></div>
    <div class="table-responsive"><table class="table table-hover mb-0 visitor-table"><thead><tr><th>Name</th><th>Actions</th><th>Visitor's address</th><th>First seen</th><th>Last seen</th><th>Current page</th><th>Chats</th><th>Misc</th></tr></thead><tbody id="onsite-visitors"><tr><td colspan="8" class="text-center text-muted py-3">Loading…</td></tr></tbody></table></div>
  </div>
</div>
<div class="row" id="chat-console" data-api="../modules/livechat/api.php"><div class="col-lg-4 mb-4"><div class="card shadow-sm"><div class="card-header font-weight-bold">Conversations</div><div class="list-group list-group-flush" id="chat-list"><div class="p-3 text-muted">Loading…</div></div></div></div><div class="col-lg-8"><div class="card shadow-sm"><div class="card-header d-flex justify-content-between"><strong id="chat-title">Select a conversation</strong><div><button id="chat-block" class="btn btn-sm btn-outline-danger mr-2" hidden><i class="fas fa-ban mr-1"></i>Block user</button><button id="chat-close" class="btn btn-sm btn-outline-secondary" hidden>Close chat</button></div></div><div id="chat-messages" class="p-3 bg-light" style="height:420px;overflow:auto"></div><form id="chat-reply" class="card-footer" hidden><div class="input-group"><div class="input-group-prepend"><button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"><i class="fas fa-comment-dots mr-1"></i>Canned</button><div class="dropdown-menu" id="chat-canned-menu"><?php $quick_result = $canned_ready ? mysql_query("SELECT title,body FROM {$pre}livechat_canned_message WHERE operator_id=0 OR operator_id=" . (int)$_SESSION['user']['id'] . " ORDER BY title") : false; while ($quick_result && ($quick = mysql_fetch_array($quick_result, MYSQLI_ASSOC))): ?><button class="dropdown-item chat-canned-choice" type="button" data-message="<?php echo htmlspecialchars(livechat_canned_plain_text($quick['body']), ENT_QUOTES, 'UTF-8') ?>"><?php echo htmlspecialchars($quick['title'], ENT_QUOTES, 'UTF-8') ?></button><?php endwhile; ?></div></div><input id="chat-text" class="form-control" maxlength="2000" required placeholder="Type a reply"><div class="input-group-append"><button class="btn btn-primary">Send</button></div></div></form></div></div></div>
<style>.visitor-table{font-size:.82rem}.visitor-table thead th{white-space:nowrap;border-top:0;background:#f8f9fc;color:#5a5c69;font-size:.72rem;text-transform:uppercase}.visitor-table td{vertical-align:middle}.visitor-page{display:block;max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.visitor-pulse{display:inline-block;width:8px;height:8px;border-radius:50%;background:#1cc88a;margin-right:5px}.visitor-action{color:#e49a00;font-size:1rem}</style>
<script>
(function(){var root=document.getElementById('live-visitor-monitor'),waiting=document.getElementById('waiting-visitors'),onsite=document.getElementById('onsite-visitors'),states=document.querySelectorAll('.visitor-monitor-state'),serverTime=Math.floor(Date.now()/1000);
function cell(row,text,className){var td=document.createElement('td');td.textContent=text;if(className)td.className=className;row.appendChild(td);return td}
function elapsed(value){var seconds=Math.max(0,serverTime-Number(value||serverTime)),hours=Math.floor(seconds/3600),minutes=Math.floor((seconds%3600)/60);return(hours?hours+'h ':'')+minutes+'m '+seconds%60+'s'}
function browser(agent){var match=(agent||'').match(/(Edg|Chrome|Firefox|Safari)\/([\d.]+)/);return match?(match[1]==='Edg'?'Edge':match[1])+' '+match[2]:'Unknown browser'}
function actionCell(row,item){var td=cell(row,'');if(item.conversation_id){var link=document.createElement('a');link.href='livechat.php?conversation='+item.conversation_id;link.className='visitor-action';link.title='Open conversation';link.innerHTML='<i class="fas fa-comment-dots"></i>';td.appendChild(link)}else if(item.invitation_id){td.innerHTML='<span class="text-warning text-nowrap"><i class="fas fa-hourglass-half mr-1"></i>Invited</span>'}else{var invite=document.createElement('button');invite.type='button';invite.className='btn btn-sm btn-outline-primary';invite.innerHTML='<i class="fas fa-comment-medical mr-1"></i>Invite';invite.onclick=function(){inviteVisitor(item,invite)};td.appendChild(invite)}return td}
function inviteVisitor(item,button){var message=prompt('Invitation message:','Hello! Would you like to chat with us?');if(message===null)return;message=message.trim();if(!message)return alert('Enter an invitation message.');button.disabled=true;fetch(root.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'operator_invite',visitor_id:item.id,message:message})}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Unable to invite visitor.');return j})}).then(refresh).catch(function(e){alert(e.message);button.disabled=false})}
function empty(target,text){target.innerHTML='';var row=document.createElement('tr'),td=cell(row,text,'text-center text-muted py-3');td.colSpan=8;target.appendChild(row)}
function render(result){serverTime=Number(result.server_time)||serverTime;waiting.innerHTML='';onsite.innerHTML='';document.getElementById('waiting-count').textContent=result.waiting.length;document.getElementById('onsite-count').textContent=result.visitors.length;if(!result.waiting.length)empty(waiting,'The list of visitors waiting is empty.');result.waiting.forEach(function(v){var row=document.createElement('tr'),name=cell(row,'');var link=document.createElement('a');link.href='livechat.php?conversation='+v.conversation_id;link.textContent=v.visitor_name||'Guest';name.appendChild(link);actionCell(row,v);cell(row,v.ip_address||'—');cell(row,'Waiting','text-warning font-weight-bold');cell(row,v.department_name||'—');cell(row,elapsed(v.first_seen));cell(row,elapsed(v.conversation_created));cell(row,browser(v.user_agent));waiting.appendChild(row)});if(!result.visitors.length)empty(onsite,'There are no visitors on site.');result.visitors.forEach(function(v){var row=document.createElement('tr');cell(row,v.visitor_name||'Guest');actionCell(row,v);cell(row,v.ip_address||'—');cell(row,elapsed(v.first_seen));cell(row,elapsed(v.last_seen));var page=cell(row,'');if(v.page_url){var link=document.createElement('a');link.href=v.page_url;link.target='_blank';link.rel='noopener';link.className='visitor-page';link.title=v.page_url;try{link.textContent=new URL(v.page_url).pathname||'/'}catch(e){link.textContent=v.page_url}page.appendChild(link)}else page.textContent='—';cell(row,String(v.chats_started||0));var misc=cell(row,'');misc.innerHTML='<span class="visitor-pulse"></span>'+browser(v.user_agent);onsite.appendChild(row)});Array.prototype.forEach.call(states,function(x){x.innerHTML='<i class="fas fa-check-circle text-success mr-1"></i>Up to date'})}
function refresh(){fetch(root.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'operator_visitors'})}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Unable to load visitors.');return j})}).then(render).catch(function(e){Array.prototype.forEach.call(states,function(x){x.textContent=e.message})})}refresh();setInterval(refresh,3000);setInterval(function(){serverTime++},1000)})();
</script>
<script>
(function(){var c=document.getElementById('chat-console'),list=document.getElementById('chat-list'),box=document.getElementById('chat-messages'),form=document.getElementById('chat-reply'),title=document.getElementById('chat-title'),closeBtn=document.getElementById('chat-close'),blockBtn=document.getElementById('chat-block'),active=Number(new URLSearchParams(location.search).get('conversation'))||0,last=0,activeStatus='',autoOpen=active>0;
function api(d){return fetch(c.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Request failed');return j})})}
function loadList(){api({action:'operator_list'}).then(function(r){list.innerHTML='';if(!r.conversations.length)list.innerHTML='<div class="p-3 text-muted">No conversations yet.</div>';r.conversations.forEach(function(x){var b=document.createElement('button');b.type='button';b.className='list-group-item list-group-item-action'+(+x.id===active?' active':'');b.innerHTML='<div class="d-flex justify-content-between"><strong></strong><small></small></div><span class="small d-block"></span><em class="small"></em>';b.querySelector('strong').textContent=x.visitor_name;b.querySelector('small').textContent=x.status;b.querySelector('span').textContent=x.last_message||'New conversation';b.querySelector('em').textContent=x.department_name||'No department';b.onclick=function(){active=+x.id;last=0;box.innerHTML='';title.textContent=x.visitor_name+(x.visitor_email?' · '+x.visitor_email:'')+(x.department_name?' · '+x.department_name:'');form.hidden=false;closeBtn.hidden=false;blockBtn.hidden=false;poll();loadList()};list.appendChild(b);if(autoOpen&&+x.id===active){autoOpen=false;b.click()}})})}
function poll(){if(!active)return;api({action:'operator_poll',conversation_id:active,after:last}).then(function(r){r.messages.forEach(function(m){var d=document.createElement('div'),meta=document.createElement('div'),body=document.createElement('div'),time=new Date(+m.created_at*1000);d.className='mb-2 p-2 rounded '+(m.sender==='operator'?'bg-primary text-white ml-auto':'bg-white');d.style.maxWidth='80%';meta.className='small font-weight-bold mb-1';meta.style.opacity='.75';meta.textContent=m.sender_name+' · '+time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});body.style.whiteSpace='pre-wrap';body.textContent=m.body;d.appendChild(meta);d.appendChild(body);box.appendChild(d);last=Math.max(last,+m.id)});if(r.messages.length)box.scrollTop=box.scrollHeight;activeStatus=r.conversation.status;form.hidden=activeStatus==='closed';closeBtn.textContent=activeStatus==='closed'?'Reopen chat':'Close chat';closeBtn.className=activeStatus==='closed'?'btn btn-sm btn-outline-success':'btn btn-sm btn-outline-secondary'}).catch(function(e){console.error(e)})}
form.onsubmit=function(e){e.preventDefault();var i=document.getElementById('chat-text');api({action:'operator_send',conversation_id:active,body:i.value}).then(function(){i.value='';poll();loadList()}).catch(function(e){alert(e.message)})};Array.prototype.forEach.call(document.querySelectorAll('.chat-canned-choice'),function(b){b.onclick=function(){var i=document.getElementById('chat-text');i.value=b.dataset.message;i.focus()}});closeBtn.onclick=function(){if(!active)return;var reopening=activeStatus==='closed',message=reopening?'Reopen this conversation?':'Close this conversation?';if(confirm(message))api({action:reopening?'operator_reopen':'operator_close',conversation_id:active}).then(function(){poll();loadList()}).catch(function(e){alert(e.message)})};blockBtn.onclick=function(){if(active&&confirm('Block this user from live chat? This also closes the conversation.'))api({action:'operator_block',conversation_id:active}).then(function(){form.hidden=true;blockBtn.hidden=true;loadList()}).catch(function(e){alert(e.message)})};loadList();setInterval(function(){loadList();poll()},3000)})();
</script>
<?php endif; include './include/footer.php'; ?>
