<?php
include '../include/settings.php';
include '../include/include.php';
include '../modules/livechat/bootstrap.php';
if (($_SESSION['login_type'] ?? $LOGIN_INVALID) == $LOGIN_INVALID) { header('Location: index.php?redirect=livechat.php'); exit; }
$operator_id = (int)($_SESSION['user']['id'] ?? 0);
$global_priv = get_row_count("SELECT COUNT(*) FROM {$pre}privilege WHERE user_id=$operator_id AND dept_id=0");
if (!$global_priv || !livechat_installed() || !livechat_enabled()) { http_response_code(403); exit('Live chat is unavailable.'); }
$conversation_id = (int)($_GET['conversation'] ?? 0);
$history_mode = !empty($_GET['history']);
if (!$conversation_id) { http_response_code(400); exit('Conversation is required.'); }
$canned = livechat_ensure_canned_messages() ? mysql_query("SELECT title,body FROM {$pre}livechat_canned_message WHERE operator_id=0 OR operator_id=$operator_id ORDER BY title") : false;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Live chat conversation</title>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet"><link href="./vendor/sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet">
<style>html,body{height:100%;margin:0;background:#f4f6fb}.chat-window{height:100%;display:flex;flex-direction:column}.chat-header{display:flex;align-items:center;min-height:68px;padding:12px 16px;background:linear-gradient(135deg,#4e73df,#6659df);color:#fff;box-shadow:0 2px 12px rgba(31,45,61,.18)}.chat-avatar{display:grid;place-items:center;width:40px;height:40px;margin-right:11px;border-radius:12px;background:rgba(255,255,255,.16)}.chat-heading{min-width:0;flex:1}.chat-heading strong,.chat-heading small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chat-heading small{color:rgba(255,255,255,.75)}.icon-button{display:inline-grid;place-items:center;width:38px;height:38px;margin-left:7px;border:1px solid rgba(255,255,255,.25);border-radius:10px;background:rgba(255,255,255,.1);color:#fff;cursor:pointer}.icon-button:hover{background:rgba(255,255,255,.22);color:#fff}.icon-button.danger:hover{background:#e74a3b}.messages{min-height:0;flex:1;overflow:auto;padding:18px;background:#f7f8fc}.message{max-width:78%;margin:8px 0;padding:10px 12px;border-radius:5px 14px 14px;background:#fff;box-shadow:0 2px 8px rgba(15,23,42,.06);white-space:pre-wrap;overflow-wrap:anywhere}.message.operator{margin-left:auto;border-radius:14px 14px 5px;background:#4e73df;color:#fff}.message-meta{margin-bottom:4px;font-size:10px;font-weight:700;opacity:.65}.typing{padding:3px 18px 8px;color:#858796;font-size:12px;background:#f7f8fc}.composer{display:flex;gap:8px;padding:12px;border-top:1px solid #e3e6f0;background:#fff}.composer input{min-width:0;flex:1}.composer button{width:44px}.canned-menu{max-height:240px;overflow:auto}</style></head><body>
<main class="chat-window" id="popup-chat" data-api="../modules/livechat/api.php" data-conversation="<?php echo $conversation_id ?>" data-history="<?php echo $history_mode?'1':'0' ?>">
<header class="chat-header"><span class="chat-avatar"><i class="fas fa-user"></i></span><div class="chat-heading"><strong id="chat-title">Loading conversation…</strong><small id="chat-details"></small></div><button class="icon-button danger" id="chat-block" title="Block visitor" aria-label="Block visitor"><i class="fas fa-ban"></i></button><button class="icon-button" id="chat-close" title="Close conversation" aria-label="Close conversation"><i class="fas fa-times"></i></button></header>
<div class="messages" id="chat-messages"></div><div class="typing" id="chat-typing" hidden><i class="fas fa-ellipsis-h mr-1"></i>Visitor is typing…</div>
<form class="composer" id="chat-reply"><div class="dropdown"><button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" title="Canned replies"><i class="fas fa-comment-dots"></i></button><div class="dropdown-menu canned-menu"><?php while ($canned && ($quick=mysql_fetch_array($canned,MYSQLI_ASSOC))): ?><button class="dropdown-item canned-choice" type="button" data-message="<?php echo htmlspecialchars(livechat_canned_plain_text($quick['body']),ENT_QUOTES,'UTF-8') ?>"><?php echo htmlspecialchars($quick['title'],ENT_QUOTES,'UTF-8') ?></button><?php endwhile; ?></div></div><input class="form-control" id="chat-text" maxlength="2000" placeholder="Type a reply" required autocomplete="off"><button class="btn btn-primary" title="Send message" aria-label="Send message"><i class="fas fa-paper-plane"></i></button></form>
</main><script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
<script>(function(){var root=document.getElementById('popup-chat'),id=+root.dataset.conversation,historyMode=root.dataset.history==='1',box=document.getElementById('chat-messages'),form=document.getElementById('chat-reply'),input=document.getElementById('chat-text'),typing=document.getElementById('chat-typing'),closeBtn=document.getElementById('chat-close'),blockBtn=document.getElementById('chat-block'),last=0,status='',typingTimer=0,lastTypingPing=0,messagesReady=false,audioContext,visitorName='Guest';if(historyMode){form.hidden=true;closeBtn.hidden=true;blockBtn.hidden=true}
function api(data){return fetch(root.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Request failed');return j})})}
function sound(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();var oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=760;gain.gain.setValueAtTime(.14,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.24);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.24)}catch(e){}}
function alertMessage(message){sound();if(document.hidden)document.title='● '+visitorName+' · New message';if('Notification'in window&&Notification.permission==='granted'){var n=new Notification('New message from '+visitorName,{body:message,tag:'lynx-popup-'+id});n.onclick=function(){window.focus()}}}
function poll(){api({action:'operator_poll',conversation_id:id,after:last}).then(function(r){var c=r.conversation;visitorName=c.visitor_name||'Guest';document.getElementById('chat-title').textContent=visitorName;document.getElementById('chat-details').textContent=(c.visitor_email?c.visitor_email+' · ':'')+(c.ip_address||'');if(!document.hidden)document.title=visitorName+' · Live chat';if(messagesReady){var incoming=r.messages.filter(function(m){return m.sender==='visitor'});if(incoming.length)alertMessage(incoming[incoming.length-1].body)}r.messages.forEach(function(m){var d=document.createElement('div'),meta=document.createElement('div'),body=document.createElement('div'),time=new Date(+m.created_at*1000);d.className='message '+m.sender;meta.className='message-meta';meta.textContent=m.sender_name+' · '+time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});body.textContent=m.body;d.appendChild(meta);d.appendChild(body);box.appendChild(d);last=Math.max(last,+m.id)});messagesReady=true;if(r.messages.length){box.scrollTop=box.scrollHeight;api({action:'operator_read',conversation_id:id,last_message_id:last}).catch(function(){})}typing.hidden=!r.visitor_typing;status=c.status;form.hidden=status==='closed';closeBtn.title=status==='closed'?'Reopen conversation':'Close conversation';closeBtn.setAttribute('aria-label',closeBtn.title);closeBtn.innerHTML=status==='closed'?'<i class="fas fa-redo"></i>':'<i class="fas fa-times"></i>'}).catch(function(e){document.getElementById('chat-details').textContent=e.message})}
form.onsubmit=function(e){e.preventDefault();api({action:'operator_typing',conversation_id:id,typing:false});api({action:'operator_send',conversation_id:id,body:input.value}).then(function(){input.value='';poll()}).catch(function(e){alert(e.message)})};input.addEventListener('input',function(){var now=Date.now();if(now-lastTypingPing>2000){lastTypingPing=now;api({action:'operator_typing',conversation_id:id,typing:true}).catch(function(){})}clearTimeout(typingTimer);typingTimer=setTimeout(function(){api({action:'operator_typing',conversation_id:id,typing:false}).catch(function(){})},3000)});Array.prototype.forEach.call(document.querySelectorAll('.canned-choice'),function(button){button.onclick=function(){input.value=button.dataset.message;input.focus();input.dispatchEvent(new Event('input'))}});closeBtn.onclick=function(){var reopening=status==='closed';if(confirm(reopening?'Reopen this conversation?':'Close this conversation?'))api({action:reopening?'operator_reopen':'operator_close',conversation_id:id}).then(poll).catch(function(e){alert(e.message)})};blockBtn.onclick=function(){if(confirm('Block this visitor and close the conversation?'))api({action:'operator_block',conversation_id:id}).then(function(){window.close()}).catch(function(e){alert(e.message)})};poll();setInterval(poll,3000)})();</script></body></html>
