<?php
include '../include/settings.php';
include '../include/include.php';
include '../modules/livechat/bootstrap.php';
include '../modules/system.php';
$HD_CURPAGE = 'livechat.php';
if (($_SESSION['login_type'] ?? $LOGIN_INVALID) == $LOGIN_INVALID) { header('Location: index.php?redirect=livechat.php'); exit; }
$global_priv = get_row_count("SELECT COUNT(*) FROM {$pre}privilege WHERE user_id='" . (int)$_SESSION['user']['id'] . "' AND dept_id='0'");
if (!$global_priv) { header("Location: $HD_URL_BROWSE"); exit; }
$installed = livechat_installed();
$enabled = $installed && livechat_enabled();
$canned_ready = $installed && livechat_ensure_canned_messages();
$script_name = 'Live Chat';
include './include/header.php';
?>
<div class="d-sm-flex align-items-center justify-content-between mb-4"><div><h1 class="h3 mb-1 text-gray-800">Live chat</h1><p class="mb-0 text-muted">Talk to visitors from the support site in real time.</p></div><a class="btn btn-outline-primary mt-3 mt-sm-0" href="livechatsettings.php"><i class="fas fa-cog mr-1"></i>Chat settings</a></div>
<?php if (!$installed): ?>
<div class="alert alert-info shadow-sm">Live Chat is not installed. <a class="alert-link" href="modules.php">Install it from Modules</a>.</div>
<?php elseif (!$enabled): ?>
<div class="alert alert-warning shadow-sm">Live Chat is disabled. <a class="alert-link" href="livechatsettings.php">Enable it in Chat settings</a>.</div>
<?php else: ?>
<div class="row" id="chat-console" data-api="../modules/livechat/api.php"><div class="col-lg-4 mb-4"><div class="card shadow-sm"><div class="card-header font-weight-bold">Conversations</div><div class="list-group list-group-flush" id="chat-list"><div class="p-3 text-muted">Loading…</div></div></div></div><div class="col-lg-8"><div class="card shadow-sm"><div class="card-header d-flex justify-content-between"><strong id="chat-title">Select a conversation</strong><div><button id="chat-block" class="btn btn-sm btn-outline-danger mr-2" hidden><i class="fas fa-ban mr-1"></i>Block user</button><button id="chat-close" class="btn btn-sm btn-outline-secondary" hidden>Close chat</button></div></div><div id="chat-messages" class="p-3 bg-light" style="height:420px;overflow:auto"></div><form id="chat-reply" class="card-footer" hidden><div class="input-group"><div class="input-group-prepend"><button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"><i class="fas fa-comment-dots mr-1"></i>Canned</button><div class="dropdown-menu" id="chat-canned-menu"><?php $quick_result = $canned_ready ? mysql_query("SELECT title,body FROM {$pre}livechat_canned_message WHERE operator_id=0 OR operator_id=" . (int)$_SESSION['user']['id'] . " ORDER BY title") : false; while ($quick_result && ($quick = mysql_fetch_array($quick_result, MYSQLI_ASSOC))): ?><button class="dropdown-item chat-canned-choice" type="button" data-message="<?php echo htmlspecialchars(livechat_canned_plain_text($quick['body']), ENT_QUOTES, 'UTF-8') ?>"><?php echo htmlspecialchars($quick['title'], ENT_QUOTES, 'UTF-8') ?></button><?php endwhile; ?></div></div><input id="chat-text" class="form-control" maxlength="2000" required placeholder="Type a reply"><div class="input-group-append"><button class="btn btn-primary">Send</button></div></div></form></div></div></div>
<script>
(function(){var c=document.getElementById('chat-console'),list=document.getElementById('chat-list'),box=document.getElementById('chat-messages'),form=document.getElementById('chat-reply'),title=document.getElementById('chat-title'),closeBtn=document.getElementById('chat-close'),blockBtn=document.getElementById('chat-block'),active=Number(new URLSearchParams(location.search).get('conversation'))||0,last=0,activeStatus='',autoOpen=active>0;
function api(d){return fetch(c.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Request failed');return j})})}
function loadList(){api({action:'operator_list'}).then(function(r){list.innerHTML='';if(!r.conversations.length)list.innerHTML='<div class="p-3 text-muted">No conversations yet.</div>';r.conversations.forEach(function(x){var b=document.createElement('button');b.type='button';b.className='list-group-item list-group-item-action'+(+x.id===active?' active':'');b.innerHTML='<div class="d-flex justify-content-between"><strong></strong><small></small></div><span class="small d-block"></span><em class="small"></em>';b.querySelector('strong').textContent=x.visitor_name;b.querySelector('small').textContent=x.status;b.querySelector('span').textContent=x.last_message||'New conversation';b.querySelector('em').textContent=x.department_name||'No department';b.onclick=function(){active=+x.id;last=0;box.innerHTML='';title.textContent=x.visitor_name+(x.visitor_email?' · '+x.visitor_email:'')+(x.department_name?' · '+x.department_name:'');form.hidden=false;closeBtn.hidden=false;blockBtn.hidden=false;poll();loadList()};list.appendChild(b);if(autoOpen&&+x.id===active){autoOpen=false;b.click()}})})}
function poll(){if(!active)return;api({action:'operator_poll',conversation_id:active,after:last}).then(function(r){r.messages.forEach(function(m){var d=document.createElement('div'),meta=document.createElement('div'),body=document.createElement('div'),time=new Date(+m.created_at*1000);d.className='mb-2 p-2 rounded '+(m.sender==='operator'?'bg-primary text-white ml-auto':'bg-white');d.style.maxWidth='80%';meta.className='small font-weight-bold mb-1';meta.style.opacity='.75';meta.textContent=m.sender_name+' · '+time.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});body.style.whiteSpace='pre-wrap';body.textContent=m.body;d.appendChild(meta);d.appendChild(body);box.appendChild(d);last=Math.max(last,+m.id)});if(r.messages.length)box.scrollTop=box.scrollHeight;activeStatus=r.conversation.status;form.hidden=activeStatus==='closed';closeBtn.textContent=activeStatus==='closed'?'Reopen chat':'Close chat';closeBtn.className=activeStatus==='closed'?'btn btn-sm btn-outline-success':'btn btn-sm btn-outline-secondary'}).catch(function(e){console.error(e)})}
form.onsubmit=function(e){e.preventDefault();var i=document.getElementById('chat-text');api({action:'operator_send',conversation_id:active,body:i.value}).then(function(){i.value='';poll();loadList()}).catch(function(e){alert(e.message)})};Array.prototype.forEach.call(document.querySelectorAll('.chat-canned-choice'),function(b){b.onclick=function(){var i=document.getElementById('chat-text');i.value=b.dataset.message;i.focus()}});closeBtn.onclick=function(){if(!active)return;var reopening=activeStatus==='closed',message=reopening?'Reopen this conversation?':'Close this conversation?';if(confirm(message))api({action:reopening?'operator_reopen':'operator_close',conversation_id:active}).then(function(){poll();loadList()}).catch(function(e){alert(e.message)})};blockBtn.onclick=function(){if(active&&confirm('Block this user from live chat? This also closes the conversation.'))api({action:'operator_block',conversation_id:active}).then(function(){form.hidden=true;blockBtn.hidden=true;loadList()}).catch(function(e){alert(e.message)})};loadList();setInterval(function(){loadList();poll()},3000)})();
</script>
<?php endif; include './include/footer.php'; ?>
