<?php
include '../include/settings.php';
include '../include/include.php';
include '../modules/livechat/bootstrap.php';
include '../modules/system.php';
$HD_CURPAGE = 'livechat.php';
if (($_SESSION['login_type'] ?? $LOGIN_INVALID) == $LOGIN_INVALID) { header('Location: index.php?redirect=livechat.php'); exit; }
$global_priv = get_row_count("SELECT COUNT(*) FROM {$pre}privilege WHERE user_id='" . (int)$_SESSION['user']['id'] . "' AND dept_id='0'");
if (!$global_priv) { header("Location: $HD_URL_BROWSE"); exit; }
$installed = livechat_installed();
$enabled = $installed && livechat_enabled();
$canned_ready = $installed && livechat_ensure_canned_messages();
$script_name = 'Live Chat';
include './include/header.php';
?>
<div class="d-sm-flex align-items-center justify-content-between mb-4"><div><h1 class="h3 mb-1 text-gray-800">Live chat</h1><p class="mb-0 text-muted">Talk to visitors from the support site in real time.</p></div><div class="mt-3 mt-sm-0"><?php if ($enabled): ?><button class="btn btn-outline-success mr-2" type="button" id="chat-notifications"><i class="fas fa-bell mr-1"></i>Enable notifications</button><?php endif; ?><a class="btn btn-outline-primary" href="livechatsettings.php"><i class="fas fa-cog mr-1"></i>Chat settings</a></div></div>
<?php if (!$installed): ?>
<div class="alert alert-info shadow-sm">Live Chat is not installed. <a class="alert-link" href="modules.php">Install it from Modules</a>.</div>
<?php elseif (!$enabled): ?>
<div class="alert alert-warning shadow-sm">Live Chat is disabled. <a class="alert-link" href="livechatsettings.php">Enable it in Chat settings</a>.</div>
<?php else: ?>
<div id="live-visitor-monitor" data-api="../modules/livechat/api.php" class="mb-4">
  <div class="card shadow-sm mb-4 border-0 waiting-section" hidden>
    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center"><div><h2 class="h5 mb-1 text-gray-900"><i class="fas fa-hourglass-half text-warning mr-2"></i>Visitors waiting <span class="badge badge-warning ml-1" id="waiting-count">0</span></h2><small class="text-muted">Visitors who started a conversation and are waiting for an operator.</small></div><span class="small text-muted visitor-monitor-state">Updating…</span></div>
    <div class="table-responsive"><table class="table table-hover mb-0 visitor-table"><thead><tr><th>Name</th><th>Actions</th><th>Visitor's address</th><th>State</th><th>Department</th><th>Total time</th><th>Waiting time</th><th>Misc</th></tr></thead><tbody id="waiting-visitors"><tr><td colspan="8" class="text-center text-muted py-3">Loading…</td></tr></tbody></table></div>
  </div>
  <div class="card shadow-sm border-0">
    <div class="card-header bg-white py-3"><h2 class="h5 mb-1 text-gray-900"><i class="fas fa-users text-primary mr-2"></i>Visitors on site <span class="badge badge-primary ml-1" id="onsite-count">0</span></h2><small class="text-muted">Visitors currently viewing a page where the live-chat widget is loaded.</small></div>
    <div class="table-responsive"><table class="table table-hover mb-0 visitor-table"><thead><tr><th>Name</th><th>Actions</th><th>Visitor's address</th><th>First seen</th><th>Last seen</th><th>Current page</th><th>Chats</th><th>Misc</th></tr></thead><tbody id="onsite-visitors"><tr><td colspan="8" class="text-center text-muted py-3">Loading…</td></tr></tbody></table></div>
  </div>
</div>
<div id="chat-console" data-api="../modules/livechat/api.php" class="card shadow-sm mb-4 border-0"><div class="card-header bg-white py-3"><h2 class="h5 mb-1 text-gray-900"><i class="fas fa-comments text-primary mr-2"></i>Conversations</h2><small class="text-muted">Select a conversation to open it in a separate chat window.</small></div><div class="list-group list-group-flush" id="chat-list"><div class="p-3 text-muted">Loading…</div></div></div>
<style>#chat-list .conversation-row{display:block;width:100%;padding:14px 16px;border:0;border-top:1px solid #edf0f5;border-radius:0;background:#fff;color:#39445a;text-align:left;transition:background .15s}#chat-list .conversation-row:hover{background:#f8faff}#chat-list .conversation-row.unread{border-left:4px solid #4e73df;background:#eef3ff;padding-left:12px}#chat-list .conversation-name{font-weight:700;color:#26324b}#chat-list .conversation-preview{display:block;max-width:680px;margin-top:3px;overflow:hidden;color:#68738a;text-overflow:ellipsis;white-space:nowrap}#chat-list .conversation-meta{color:#8a94a8;font-size:.78rem}#chat-list .unread-badge{display:inline-grid;place-items:center;min-width:22px;height:22px;margin-left:8px;padding:0 6px;border-radius:11px;background:#e74a3b;color:#fff;font-size:.72rem;font-weight:700}</style>
<style>#chat-console>.col-lg-4{flex:0 0 100%;max-width:100%}#chat-console>.col-lg-8{display:none}.visitor-table{font-size:.82rem}.visitor-table thead th{white-space:nowrap;border-top:0;background:#f8f9fc;color:#5a5c69;font-size:.72rem;text-transform:uppercase}.visitor-table td{vertical-align:middle}.visitor-page{display:block;max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.visitor-pulse{display:inline-block;width:8px;height:8px;border-radius:50%;background:#1cc88a;margin-right:5px}.visitor-action{color:#e49a00;font-size:1rem}</style>
<script>
(function(){var root=document.getElementById('live-visitor-monitor'),waiting=document.getElementById('waiting-visitors'),onsite=document.getElementById('onsite-visitors'),states=document.querySelectorAll('.visitor-monitor-state'),serverTime=Math.floor(Date.now()/1000);
function cell(row,text,className){var td=document.createElement('td');td.textContent=text;if(className)td.className=className;row.appendChild(td);return td}
function elapsed(value){var seconds=Math.max(0,serverTime-Number(value||serverTime)),hours=Math.floor(seconds/3600),minutes=Math.floor((seconds%3600)/60);return(hours?hours+'h ':'')+minutes+'m '+seconds%60+'s'}
function browser(agent){var match=(agent||'').match(/(Edg|Chrome|Firefox|Safari)\/([\d.]+)/);return match?(match[1]==='Edg'?'Edge':match[1])+' '+match[2]:'Unknown browser'}
function actionCell(row,item){var td=cell(row,'');if(item.conversation_id){var link=document.createElement('a');link.href='livechatwindow.php?conversation='+item.conversation_id;link.className='visitor-action';link.title='Open conversation';link.innerHTML='<i class="fas fa-comment-dots"></i>';link.onclick=function(e){e.preventDefault();window.open(link.href,'lynx_chat_'+item.conversation_id,'popup=yes,width=520,height=700,resizable=yes,scrollbars=no')};td.appendChild(link)}else if(item.invitation_id){td.innerHTML='<span class="text-warning text-nowrap"><i class="fas fa-hourglass-half mr-1"></i>Invited</span>'}else{var invite=document.createElement('button');invite.type='button';invite.className='btn btn-sm btn-outline-primary';invite.innerHTML='<i class="fas fa-comment-medical mr-1"></i>Invite';invite.onclick=function(){inviteVisitor(item,invite)};td.appendChild(invite)}return td}
function inviteVisitor(item,button){var message=prompt('Invitation message:','Hello! Would you like to chat with us?');if(message===null)return;message=message.trim();if(!message)return alert('Enter an invitation message.');button.disabled=true;fetch(root.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'operator_invite',visitor_id:item.id,message:message})}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Unable to invite visitor.');return j})}).then(refresh).catch(function(e){alert(e.message);button.disabled=false})}
function empty(target,text){target.innerHTML='';var row=document.createElement('tr'),td=cell(row,text,'text-center text-muted py-3');td.colSpan=8;target.appendChild(row)}
function render(result){serverTime=Number(result.server_time)||serverTime;waiting.innerHTML='';onsite.innerHTML='';document.getElementById('waiting-count').textContent=result.waiting.length;document.getElementById('onsite-count').textContent=result.visitors.length;if(!result.waiting.length)empty(waiting,'The list of visitors waiting is empty.');result.waiting.forEach(function(v){var row=document.createElement('tr'),name=cell(row,'');var link=document.createElement('a');link.href='livechat.php?conversation='+v.conversation_id;link.textContent=v.visitor_name||'Guest';name.appendChild(link);actionCell(row,v);cell(row,v.ip_address||'—');cell(row,'Waiting','text-warning font-weight-bold');cell(row,v.department_name||'—');cell(row,elapsed(v.first_seen));cell(row,elapsed(v.conversation_created));cell(row,browser(v.user_agent));waiting.appendChild(row)});if(!result.visitors.length)empty(onsite,'There are no visitors on site.');result.visitors.forEach(function(v){var row=document.createElement('tr');cell(row,v.visitor_name||'Guest');actionCell(row,v);cell(row,v.ip_address||'—');cell(row,elapsed(v.first_seen));cell(row,elapsed(v.last_seen));var page=cell(row,'');if(v.page_url){var link=document.createElement('a');link.href=v.page_url;link.target='_blank';link.rel='noopener';link.className='visitor-page';link.title=v.page_url;try{link.textContent=new URL(v.page_url).pathname||'/'}catch(e){link.textContent=v.page_url}page.appendChild(link)}else page.textContent='—';cell(row,String(v.chats_started||0));var misc=cell(row,'');misc.innerHTML='<span class="visitor-pulse"></span>'+browser(v.user_agent);onsite.appendChild(row)});Array.prototype.forEach.call(states,function(x){x.innerHTML='<i class="fas fa-check-circle text-success mr-1"></i>Up to date'})}
function refresh(){fetch(root.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'operator_visitors'})}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Unable to load visitors.');return j})}).then(render).catch(function(e){Array.prototype.forEach.call(states,function(x){x.textContent=e.message})})}refresh();setInterval(refresh,3000);setInterval(function(){serverTime++},1000)})();
</script>
<script>
(function(){var c=document.getElementById('chat-console'),list=document.getElementById('chat-list'),notifyBtn=document.getElementById('chat-notifications'),requested=Number(new URLSearchParams(location.search).get('conversation'))||0,listReady=false,knownMessages={},audioContext;
function api(d){return fetch(c.dataset.api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)}).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||'Request failed');return j})})}
function openChat(id){var popup=window.open('livechatwindow.php?conversation='+id,'lynx_chat_'+id,'popup=yes,width=520,height=700,resizable=yes,scrollbars=no');if(popup)popup.focus()}
function sound(){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();var oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=740;gain.gain.setValueAtTime(.12,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.22);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.22)}catch(e){}}
function desktop(titleText,body,id){sound();if('Notification'in window&&Notification.permission==='granted'){var n=new Notification(titleText,{body:body,tag:'lynx-livechat-'+id});n.onclick=function(){window.focus();openChat(id)}}}
if(!('Notification'in window)){notifyBtn.hidden=true}else{if(Notification.permission==='granted')notifyBtn.innerHTML='<i class="fas fa-bell text-success mr-1"></i>Notifications enabled';notifyBtn.onclick=function(){sound();Notification.requestPermission().then(function(permission){if(permission==='granted')notifyBtn.innerHTML='<i class="fas fa-bell text-success mr-1"></i>Notifications enabled';else notifyBtn.textContent='Notifications blocked'})}}
function loadList(){api({action:'operator_list'}).then(function(r){r.conversations.forEach(function(x){var id=+x.id,unread=+x.unread_count||0,previous=knownMessages[id]||0;if(listReady&&unread>previous)desktop('New message from '+x.visitor_name,x.last_message||'New message',id);knownMessages[id]=unread});listReady=true;list.innerHTML='';if(!r.conversations.length)list.innerHTML='<div class="p-3 text-muted">No conversations yet.</div>';r.conversations.forEach(function(x){var unread=+x.unread_count||0,b=document.createElement('button'),top=document.createElement('div'),name=document.createElement('span'),right=document.createElement('span'),preview=document.createElement('span'),meta=document.createElement('span');b.type='button';b.className='conversation-row'+(unread?' unread':'');top.className='d-flex justify-content-between align-items-center';name.className='conversation-name';name.textContent=x.visitor_name||'Guest';right.className='d-flex align-items-center conversation-meta';right.appendChild(document.createTextNode(x.status));if(unread){var badge=document.createElement('span');badge.className='unread-badge';badge.textContent=unread>99?'99+':unread;right.appendChild(badge)}top.appendChild(name);top.appendChild(right);preview.className='conversation-preview';preview.textContent=x.last_message||'New conversation';meta.className='conversation-meta font-italic';meta.textContent=(x.department_name||'No department')+(x.last_message_at?' · '+new Date(+x.last_message_at*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'');b.appendChild(top);b.appendChild(preview);b.appendChild(meta);b.onclick=function(){openChat(+x.id)};list.appendChild(b)});if(requested){openChat(requested);requested=0;if(history.replaceState)history.replaceState(null,'','livechat.php')}})}
loadList();setInterval(loadList,3000)})();
</script>
<?php endif; include './include/footer.php'; ?>
