<?php
$ticket_id = $_GET['id'];
$status_labels = array($HD_STATUS_OPEN => 'Open', $HD_STATUS_CLOSED => 'Closed', $HD_STATUS_HELD => 'Held');
$priority_labels = array($PRIORITY_LOW => 'Low', $PRIORITY_MEDIUM => 'Medium', $PRIORITY_HIGH => 'High');
$status_label = $status_labels[$row['status']] ?? 'Unknown';
$priority_label = $priority_labels[$row['priority']] ?? 'Unknown';
$department_name = 'Internal message';
if( $is_ticket )
{
  $department_row = mysql_fetch_array(mysql_query("SELECT name FROM {$pre}dept WHERE ( id = '{$row['dept_id']}' )"));
  $department_name = $department_row[0] ?? 'Unknown department';
}
?>
<?php if(($_GET['replied'] ?? '') == '1'): ?><div class="alert alert-success"><i class="fas fa-check-circle mr-2"></i>Reply posted successfully.</div><?php endif; ?>
<div class="d-flex flex-column flex-xl-row align-items-xl-start justify-content-between mb-4">
  <div class="mb-3 mb-xl-0"><div class="d-flex flex-wrap align-items-center mb-2"><span class="badge badge-primary mr-2">#<?php echo field($ticket_id) ?></span><span class="badge badge-<?php echo $row['status'] == $HD_STATUS_OPEN ? 'success' : ($row['status'] == $HD_STATUS_HELD ? 'warning' : 'secondary') ?>"><?php echo $status_label ?></span></div><h1 class="h3 text-gray-800 mb-1"><?php echo field($row['subject']) ?></h1><p class="text-muted mb-0">Created <?php echo date('M j, Y \a\t g:i a', $row['date']) ?><?php if($is_ticket): ?> by <a href="mailto:<?php echo field($row['email']) ?>"><?php echo field($row['name']) ?></a><?php endif; ?></p></div>
  <div class="d-flex flex-wrap"><a class="btn btn-primary btn-sm mr-2 mb-2" href="#reply"><i class="fas fa-reply mr-1"></i>Reply</a><a class="btn btn-outline-secondary btn-sm mr-2 mb-2" href="printable.php?id=<?php echo urlencode($ticket_id) ?>" target="_blank"><i class="fas fa-print mr-1"></i>Print</a><?php if($data['uploads']): ?><a class="btn btn-outline-secondary btn-sm mr-2 mb-2" href="#attach"><i class="fas fa-paperclip mr-1"></i>Attach</a><?php endif; ?><a class="btn btn-outline-danger btn-sm mb-2" href="<?php echo field($HD_CURPAGE) ?>?cmd=delete&amp;id=<?php echo urlencode($ticket_id) ?>" onclick="return confirm('Delete this <?php echo $is_ticket ? 'ticket' : 'thread' ?>?')"><i class="fas fa-trash mr-1"></i>Delete</a></div>
</div>

<?php if($is_ticket): ?>
<section class="card shadow-sm mb-4"><div class="card-header"><h2 class="h6 mb-0">Ticket controls</h2></div><div class="card-body"><form action="<?php echo field($HD_CURPAGE) ?>" method="post"><input type="hidden" name="id" value="<?php echo field($ticket_id) ?>"><input type="hidden" name="cmd" value="update"><div class="form-row align-items-end"><div class="form-group col-lg-4"><label for="ticket-department">Move to department</label><select class="form-control" id="ticket-department" name="department"><option value="-1">Keep <?php echo field($department_name) ?></option><?php $res_dept = mysql_query("SELECT id, name FROM {$pre}dept ORDER BY sortnum"); while($row_dept = mysql_fetch_array($res_dept)): if($row_dept['id'] != $row['dept_id']): ?><option value="<?php echo (int)$row_dept['id'] ?>"><?php echo field($row_dept['name']) ?></option><?php endif; endwhile; ?></select></div><div class="form-group col-md-4 col-lg-3"><label for="ticket-priority">Priority</label><select class="form-control" id="ticket-priority" name="priority"><?php foreach($priority_labels as $value => $label): ?><option value="<?php echo $value ?>" <?php if($row['priority'] == $value) echo 'selected' ?>><?php echo $label ?></option><?php endforeach; ?></select></div><div class="form-group col-md-4 col-lg-3"><label for="ticket-status">Status</label><select class="form-control" id="ticket-status" name="status"><?php foreach($status_labels as $value => $label): ?><option value="<?php echo $value ?>" <?php if($row['status'] == $value) echo 'selected' ?>><?php echo $label ?></option><?php endforeach; ?></select></div><div class="form-group col-md-4 col-lg-2"><button class="btn btn-primary btn-block" type="submit">Update</button></div></div></form></div></section>
<?php endif; ?>

<div class="row">
  <div class="col-xl-8">
    <section class="card shadow-sm mb-4"><div class="card-header d-flex justify-content-between align-items-center"><h2 class="h6 mb-0">Conversation</h2><span class="small text-muted">Newest first</span></div><div class="card-body bg-light">
    <?php
    $first_row = mysql_fetch_array(mysql_query("SELECT id FROM {$pre}post WHERE ( ticket_id = '{$row['id']}' ) ORDER BY date LIMIT 1"));
    $first_id = $first_row[0] ?? 0;
    $res_post = mysql_query("SELECT * FROM {$pre}post WHERE ( ticket_id = '{$row['id']}' ) ORDER BY date DESC");
    $priv = get_row_count("SELECT COUNT(*) FROM {$pre}privilege WHERE ( user_id = '{$_SESSION['user']['id']}' && admin = '1' && (dept_id = '{$row['dept_id']}' || dept_id = '0') )");
    while($row_post = mysql_fetch_array($res_post)):
      $post_subject = trim($row_post['subject']) === '' ? 'No subject' : $row_post['subject'];
      $is_customer = $row_post['user_id'] == -1;
      $author = $row['name'];
      $author_meta = $is_customer ? $row['email'] : 'Staff';
      if(!$is_customer) { $author_row = mysql_fetch_array(mysql_query("SELECT name, signature FROM {$pre}user WHERE ( id = '{$row_post['user_id']}' )")) ?: array('name'=>'Unknown user','signature'=>''); $author = $author_row['name']; if(trim($author_row['signature']) !== '') $row_post['message'] .= "\n\n{$author_row['signature']}"; }
      $post_message = render_editor_content($row_post['message'], !empty($data['tags']));
      $can_delete = ($is_ticket && $priv && $row_post['id'] != $first_id) || (!$is_ticket && $row_post['user_id'] == $_SESSION['user']['id'] && $row_post['id'] != $first_id);
    ?>
      <article class="card border-left-<?php echo $row_post['private'] ? 'warning' : ($is_customer ? 'primary' : 'success') ?> shadow-sm mb-3"><div class="card-header bg-white d-flex flex-column flex-md-row justify-content-between"><div><strong><?php echo field($post_subject) ?></strong><small class="d-block text-muted"><?php echo field($author) ?> · <?php echo field($author_meta) ?><?php if($row_post['private']): ?> · Private note<?php endif; ?></small></div><time class="small text-muted mt-2 mt-md-0"><?php echo date('M j, Y g:i a', $row_post['date']) ?></time></div><div class="card-body ticket-copy"><?php echo $post_message ?></div><?php if($can_delete): ?><div class="card-footer bg-white text-right"><a class="text-danger small" href="<?php echo field($HD_CURPAGE) ?>?cmd=deletepost&amp;postid=<?php echo (int)$row_post['id'] ?>&amp;id=<?php echo urlencode($ticket_id) ?>" onclick="return confirm('Delete this post?')"><i class="fas fa-trash mr-1"></i>Delete post</a></div><?php endif; ?></article>
    <?php endwhile; ?>
    </div></section>

    <section class="card shadow-sm mb-4" id="reply"><div class="card-header"><h2 class="h6 mb-0">Post reply</h2></div><div class="card-body">
      <?php if($is_ticket): $res_reply = mysql_query("SELECT * FROM {$pre}reply WHERE ( dept_id = '-1' )"); if(mysql_num_rows($res_reply)): ?><div class="form-group"><label for="predefined-reply">Predefined reply</label><select class="form-control" id="predefined-reply" onchange="document.predefinedreply.message.value=this.value;if(window.tinymce&&tinymce.get('reply-message'))tinymce.get('reply-message').setContent(this.value)"><option value="">Choose a saved reply</option><?php while($saved_reply=mysql_fetch_array($res_reply)): ?><option value="<?php echo field($saved_reply['reply']) ?>"><?php echo field($saved_reply['phrase']) ?></option><?php endwhile; ?></select></div><?php endif; endif; ?>
      <form name="predefinedreply" action="<?php echo field($HD_CURPAGE) ?>" method="post"><input type="hidden" name="id" value="<?php echo field($ticket_id) ?>"><input type="hidden" name="cmd" value="reply"><div class="form-group"><label for="reply-subject">Subject</label><input class="form-control" id="reply-subject" type="text" name="subject" value="<?php echo field($_POST['subject'] ?? '') ?>"></div><div class="form-group"><div class="d-flex justify-content-between"><label for="reply-message">Message</label><?php if($data['tags']): ?><a class="small" href="<?php echo field($HD_URL_TICKET_TAGS) ?>" target="_blank">Message tags</a><?php endif; ?></div><textarea class="form-control" id="reply-message" name="message" rows="8"><?php echo field($_POST['message'] ?? '') ?></textarea></div>
      <?php if($is_ticket): ?><div class="border rounded p-3 mb-3"><div class="custom-control custom-checkbox mb-3"><input class="custom-control-input" id="reply-save" type="checkbox" name="save"><label class="custom-control-label" for="reply-save">Save as predefined reply</label></div><input class="form-control form-control-sm mb-3" type="text" name="replyname" placeholder="Predefined reply name"><div class="custom-control custom-checkbox mb-3"><input class="custom-control-input" id="reply-close" type="checkbox" name="close"><label class="custom-control-label" for="reply-close">Close ticket after replying</label></div><div class="custom-control custom-checkbox"><input class="custom-control-input" id="reply-private" type="checkbox" name="private"><label class="custom-control-label" for="reply-private">Post as private note</label></div></div><?php endif; ?><div class="text-right"><button class="btn btn-light mr-2" type="reset">Reset</button><button class="btn btn-primary" type="submit"><i class="fas fa-paper-plane mr-1"></i>Post reply</button></div></form>
    </div></section>
  </div>

  <aside class="col-xl-4">
    <section class="card shadow-sm mb-4"><div class="card-header"><h2 class="h6 mb-0">Details</h2></div><div class="card-body"><dl class="row mb-0"><dt class="col-5">Department</dt><dd class="col-7"><?php echo field($department_name) ?></dd><dt class="col-5">Priority</dt><dd class="col-7"><?php echo $priority_label ?></dd><dt class="col-5">Status</dt><dd class="col-7"><?php echo $status_label ?></dd><?php if($is_ticket): ?><dt class="col-5">Requester</dt><dd class="col-7"><?php echo field($row['name']) ?></dd><dt class="col-5">Email</dt><dd class="col-7 text-break"><a href="mailto:<?php echo field($row['email']) ?>"><?php echo field($row['email']) ?></a></dd><?php endif; ?></dl><?php if($is_ticket && trim($row['custom']) !== ''): ?><hr><h3 class="h6">Custom fields</h3><dl class="mb-0"><?php $fields=explode("\n",$row['custom']); for($i=0;$i<count($fields);$i+=2): if(trim($fields[$i]) !== ''): ?><dt><?php echo field($fields[$i]) ?></dt><dd><?php echo field($fields[$i+1] ?? '') ?></dd><?php endif; endfor; ?></dl><?php endif; ?></div></section>
    <?php if($is_ticket): ?><section class="card shadow-sm mb-4"><div class="card-header"><h2 class="h6 mb-0">Assign flag</h2></div><div class="card-body"><form action="<?php echo field($HD_CURPAGE) ?>" method="post"><input type="hidden" name="id" value="<?php echo field($ticket_id) ?>"><input type="hidden" name="cmd" value="flag"><div class="input-group"><select class="form-control" name="flag"><option value="-1" <?php if($row['flag']==-1) echo 'selected' ?>>No flag</option><option value="0" <?php if($row['flag']==0) echo 'selected' ?>>All users</option><?php $res_users=mysql_query("SELECT DISTINCT user.id, user.* FROM {$pre}user AS user, {$pre}privilege AS priv WHERE ( priv.user_id = user.id && (priv.dept_id = '{$row['dept_id']}' || priv.dept_id = 0) )"); while($flag_user=mysql_fetch_array($res_users)): ?><option value="<?php echo (int)$flag_user['id'] ?>" <?php if($row['flag']==$flag_user['id']) echo 'selected' ?>><?php echo field($flag_user['name']) ?></option><?php endwhile; ?></select><div class="input-group-append"><button class="btn btn-outline-primary" type="submit">Save</button></div></div></form></div></section><?php endif; ?>
    <?php $files=array(); if($dir=@opendir("{$HD_TICKET_FILES}/{$row['id']}")) { while($file=readdir($dir)) if($file!='.'&&$file!='..') $files[]=array(filectime("{$HD_TICKET_FILES}/{$row['id']}/{$file}"),$file); closedir($dir); usort($files,'attach_sort'); } ?>
    <section class="card shadow-sm mb-4" id="attach"><div class="card-header"><h2 class="h6 mb-0">Attachments</h2></div><div class="card-body"><?php if($files): ?><div class="list-group list-group-flush mb-3"><?php foreach($files as $file): ?><a class="list-group-item list-group-item-action px-0" href="<?php echo field($HD_URL_ATTACHMENT) ?>?id=<?php echo urlencode($ticket_id) ?>&amp;email=<?php echo urlencode($row['email']) ?>&amp;file=<?php echo urlencode($file[1]) ?>" target="_blank"><i class="fas fa-paperclip mr-2"></i><?php echo field($file[1]) ?></a><?php endforeach; ?></div><?php else: ?><p class="text-muted small">No attachments.</p><?php endif; ?><?php if($data['uploads']): ?><form enctype="multipart/form-data" action="<?php echo field($HD_CURPAGE) ?>" method="post"><input type="hidden" name="cmd" value="attach"><input type="hidden" name="id" value="<?php echo field($ticket_id) ?>"><div class="custom-file mb-3"><input class="custom-file-input" id="ticket-file" name="userfile" type="file" required><label class="custom-file-label" for="ticket-file">Choose file</label></div><button class="btn btn-outline-primary btn-sm" type="submit">Upload</button></form><?php endif; ?></div></section>
    <section class="card shadow-sm mb-4" id="cc"><div class="card-header"><h2 class="h6 mb-0">Carbon copy</h2></div><div class="card-body"><form action="<?php echo field($HD_CURPAGE) ?>" method="post"><input type="hidden" name="cmd" value="cc"><input type="hidden" name="id" value="<?php echo field($ticket_id) ?>"><div class="form-group"><label for="ticket-cc">Email addresses</label><input class="form-control" id="ticket-cc" type="text" name="cc" value="<?php echo field($row['cc']) ?>"><small class="form-text text-muted">Separate addresses with spaces.</small></div><button class="btn btn-outline-primary btn-sm" type="submit">Update CC</button></form></div></section>
  </aside>
</div>

<?php if($is_ticket && mysql_num_rows($res_others)): ?>
<section class="card shadow-sm mb-4" id="others"><div class="card-header"><h2 class="h6 mb-0">Customer history</h2></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Ticket</th><th>Subject</th><th>Department</th><th>Date</th></tr></thead><tbody><?php while($other=mysql_fetch_array($res_others)): $other_dept=mysql_fetch_array(mysql_query("SELECT name FROM {$pre}dept WHERE ( id = '{$other['dept_id']}' )")); ?><tr><td><a href="<?php echo field($CURPAGE) ?>?cmd=view&amp;id=<?php echo urlencode($other['ticket_id']) ?>"><?php echo field($other['ticket_id']) ?></a></td><td><a href="<?php echo field($CURPAGE) ?>?cmd=view&amp;id=<?php echo urlencode($other['ticket_id']) ?>"><?php echo field($other['subject']) ?></a></td><td><?php echo field($other_dept[0] ?? 'Unknown') ?></td><td><?php echo date('M j, Y',$other['date']) ?></td></tr><?php endwhile; ?></tbody></table></div></section>
<?php endif; ?>
